name: Extract and check data

on:
  schedule:
    - cron:  '0 0 7 * *'
  push:
    branches-ignore:
      - 'gh-pages'

      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Setup python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and extract data
      run: |
        ./install.sh
        export PATH=$PATH:$PWD/
        xsv --version
        osm_transit_extractor --version
        python -m pip install --upgrade pip
        python -m pip install requests
        # install gdal
        sudo add-apt-repository --yes ppa:ubuntugis/ppa
        sudo apt-get --quiet update
        sudo apt-get install --yes libgdal-dev gdal-bin
        ogr2ogr --version
        ./extract_lines.sh
        test `cat output/lines.csv | xsv count` -ge 2 #fail if less than 2 lines
    - name: Check data
      run: python validator.py > output/qa.md
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output
